set exrc
set clipboard=
set lbr " word break
set secure
set tabstop=4
set shiftwidth=4
set expandtab
set incsearch
set autoindent
set scrolloff=5
set nowrap
" set smartindent
set t_Co=256
"set number
set foldmethod=syntax
set nofoldenable
"set cursorline

syntax on
colorscheme default

" undo
if has('persistent_undo')
  set undofile
  set undodir=$HOME/.vim/undo
endif     

let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0

" Plugins
filetype plugin indent on

" Commands
command! W :w
command! Q :q
command! -nargs=* -complete=file Sp :tabnew <args>

" Mappings
nmap <F1> <nop>
imap <F1> <nop>
nnoremap <F3> :call GoToDefinitionOfCurrentWord()<cr>zz
nnoremap <C-F3> :call GoToDefinitionOfCurrentWord(1, 0)<cr>zz
nnoremap <S-F3> :call GoToDefinitionOfCurrentWord(0, 1)<cr>zz
nnoremap <C-S-F3> :call GoToDefinitionOfCurrentWord(1, 1)<cr>zz
nnoremap <F4> :call SourceHeaderSwap()<cr>
nnoremap <S-F4> :call SourceHeaderSwap(1)<cr>
nnoremap <F5> :make!<cr>
nnoremap <F6> :!make run<cr>

nnoremap <silent> z. :<C-u>normal! zszH<cr>

nnoremap <C-t> :tabnew<cr>
inoremap <C-t> <ESC>:tabnew<cr>

" ctrl+r replace all from visual
vnoremap <C-r> "hy:%s/<C-r>h//gc<left><left><left>

nnoremap <S-Up> <nop>
nnoremap <S-Down> <nop>
nnoremap <S-Left> <nop>
nnoremap <S-Right> <nop>
vnoremap <S-Up> <nop>
vnoremap <S-Down> <nop>
vnoremap <S-Left> <nop>
vnoremap <S-Right> <nop>
inoremap <S-Up> <nop>
inoremap <S-Down> <nop>
inoremap <S-Left> <nop>
inoremap <S-Right> <nop>

