set exrc
set clipboard=
set lbr " word break
set secure
set tabstop=4
set shiftwidth=4
set expandtab
set incsearch
set autoindent
set scrolloff=5
set nowrap
" set smartindent
set t_Co=256
"set number
set foldmethod=syntax
set nofoldenable
"set cursorline

syntax on
colorscheme default

" undo
if has('persistent_undo')
  set undofile
  set undodir=$HOME/.vim/undo
endif     

" Netrw settings
let g:netrw_banner = 0
"let g:netrw_browse_split = 1
let g:netrw_winsize = 20
let g:netrw_liststyle = 3
let g:netrw_altv = 1

let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0

autocmd FileType netrw setl bufhidden=delete

" Plugins
filetype plugin indent on

" Commands
command! W :w
command! Q :q
command! -nargs=* Sp :tabnew <args>

" Mappings
nmap <F1> <nop>
imap <F1> <nop>
nnoremap <F3> :Lex<cr>
nnoremap <F5> :make!<cr>
nnoremap <F6> :!make run<cr>

nnoremap <F4> :call SourceHeaderSwap()<cr>

nnoremap <C-t> :tabnew<CR>
inoremap <C-t> <ESC>:tabnew<CR>

" execute pathogen#infect()
